x-env: &env
  CARTESI_LOG_LEVEL: info
  CARTESI_BLOCKCHAIN_HTTP_ENDPOINT: http://ethereum_provider:8545
  CARTESI_BLOCKCHAIN_WS_ENDPOINT: ws://ethereum_provider:8545
  CARTESI_BLOCKCHAIN_ID: 13370
  CARTESI_CONTRACTS_INPUT_BOX_ADDRESS: 0xc7007368E1b9929488744fa4dea7BcAEea000051
  CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS: 0xC7003566dD09Aa0fC0Ce201aC2769aFAe3BF0051
  CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS: 0xc7000e3A627f91AFDE0ba7F79dbcB41bF1EA0051
  CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS: 0xC700bc767f8A21Dad91cB13CF1F629C257850051
  CARTESI_DATABASE_CONNECTION: postgres://postgres:password@database:5432/rollupsdb?sslmode=disable
  CARTESI_AUTH_MNEMONIC: "test test test test test test test test test test test junk"

services:
  ethereum_provider:
    image: cartesi/rollups-node-devnet:devel
    networks:
      - devnet
    ports:
      - 8545:8545

  database:
    image: postgres:17-alpine
    shm_size: 128mb
    networks:
      - devnet
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rollupsdb || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rollupsdb

  migration:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-cli db init
    depends_on:
      database:
        condition: service_healthy
    networks:
      - devnet
    restart: "no"
    environment:
      <<: *env

  evmreader:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-evm-reader
    depends_on:
      database:
        condition: service_healthy
      ethereum_provider:
        condition: service_healthy
    networks:
      - devnet
    ports:
      - "10001:10001" # Supervisor
    environment:
      <<: *env

  advancer:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-advancer
    depends_on:
      database:
        condition: service_healthy
      ethereum_provider:
        condition: service_healthy
    volumes:
      - node_data:/var/lib/cartesi-rollups-node/data
    networks:
      - devnet
    ports:
      - "10002:10002" # Supervisor
      - "10012:10012" # Inspect Service
    environment:
      <<: *env

  validator:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-validator
    depends_on:
      database:
        condition: service_healthy
    networks:
      - devnet
    ports:
      - "10003:10003" # Supervisor
    environment:
      <<: *env

  claimer:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-claimer
    depends_on:
      database:
        condition: service_healthy
      ethereum_provider:
        condition: service_healthy
    networks:
      - devnet
    ports:
      - "10004:10004" # Supervisor
    environment:
      <<: *env

  jsonrpc-api:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-jsonrpc-api
    depends_on:
      database:
        condition: service_healthy
    networks:
      - devnet
    ports:
      - "10005:10005" # Supervisor
      - "10011:10011" # Jsonrpc API service
    environment:
      <<: *env
volumes:
  node_data:

networks:
  devnet:
