x-env: &env
  CARTESI_LOG_LEVEL: info
  CARTESI_BLOCKCHAIN_HTTP_ENDPOINT: http://ethereum_provider:8545
  CARTESI_BLOCKCHAIN_WS_ENDPOINT: ws://ethereum_provider:8545
  CARTESI_BLOCKCHAIN_ID: 13370
  CARTESI_CONTRACTS_INPUT_BOX_ADDRESS: 0xc70074BDD26d8cF983Ca6A5b89b8db52D5850051
  CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS: 0xC7003566dD09Aa0fC0Ce201aC2769aFAe3BF0051
  CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS: 0xc7006f70875BaDe89032001262A846D3Ee160051
  CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS: 0xc700285Ab555eeB5201BC00CFD4b2CC8DED90051
  CARTESI_DATABASE_CONNECTION: postgres://postgres:password@database:5432/rollupsdb?sslmode=disable
  CARTESI_AUTH_MNEMONIC: "test test test test test test test test test test test junk"

services:
  ethereum_provider:
    image: cartesi/rollups-node-devnet:devel
    networks:
      - devnet
    ports:
      - 8545:8545

  database:
    image: postgres:17-alpine
    shm_size: 128mb
    networks:
      - devnet
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rollupsdb || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rollupsdb

  migration:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-cli db init
    depends_on:
      database:
        condition: service_healthy
    networks:
      - devnet
    restart: "no"
    environment:
      <<: *env

  node:
    image: cartesi/rollups-node:devel
    command: cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
      ethereum_provider:
        condition: service_healthy
    volumes:
      - node_data:/var/lib/cartesi-rollups-node/data
    networks:
      - devnet
    ports:
      - "10000:10000" # Supervisor
      - "10011:10011" # Jsonrpc API service
      - "10012:10012" # Inspect Service
    environment:
      <<: *env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/readyz"]
      interval: 2s
      timeout: 60s
      retries: 20
  grafana:
    image: grafana/grafana-enterprise
    depends_on:
      node:
        condition: service_healthy
    networks:
      - devnet
    ports:
      - "3000:3000" # web UI

  prometheus:
    image: prom/prometheus
    depends_on:
      node:
        condition: service_healthy
    volumes:
      - ${PWD}/dev/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - devnet
    ports:
      - "9090:9090" #



volumes:
  node_data:

networks:
  devnet:
