//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var SnapshotPolicy = &struct {
	None       postgres.StringExpression
	EveryInput postgres.StringExpression
	EveryEpoch postgres.StringExpression
}{
	None:       postgres.NewEnumValue("NONE"),
	EveryInput: postgres.NewEnumValue("EVERY_INPUT"),
	EveryEpoch: postgres.NewEnumValue("EVERY_EPOCH"),
}
